### ISSUE TITLE
Exception on Assert

### ISSUE THREAD

**Issue by ed-holland** [abapGit/dependencies#10]
I'm not familliar with the Assert statement. It gives the following exception
![image](https://user-images.githubusercontent.com/53995991/84597679-ee3b1200-ae65-11ea-9a2a-c1c4a971575f.png)

![image](https://user-images.githubusercontent.com/53995991/84597696-06129600-ae66-11ea-89b9-7842438f6761.png)

Error showing "no check-point group used".

The ".abapgit.xml" file exists. Debugger shows that it found the entry.

**Comment by larshp** [comment]
start it with a almost empty repository, ie. no existing abapgit code in it

from the readme:
> Warning: Do not specify the git repository of the package as the target!

everything in the target repository will be overwritten, ie. there should not be any `.abapgit.xml` in the target repository

**Comment by ed-holland** [comment]
Ok, i've deleted the abapgit config file.

**Comment by larshp** [comment]
should probably change it to an error message, or add a comment in the code

**Comment by ed-holland** [comment]
When i run the depency generator for different packages, will the resulting repository have all the dependent objects?

**Comment by larshp** [comment]
the report takes one package as input, finds the dependencies for the package, and overwrites everything in the remote repository

but extending the report to take multiple packages as input would be a nice new feature -> new issue
