### ISSUE TITLE
Exception generating Class code

### ISSUE THREAD

**Issue by ed-holland** [abapGit/dependencies#21]
Exception:
![image](https://user-images.githubusercontent.com/53995991/86401505-9fd1a400-bcaa-11ea-9fce-4f2890b2f70c.png)

v_class = GLE_IF_ECS_CONSTANTS

Note: Requires draft code off pull #20 although issue is caused in original code.

**Comment by larshp** [comment]
DEPRECATED
use https://github.com/abaplint/abaplint-abap-backend instead

**Comment by ed-holland** [comment]
can you point me to the dependency generator of backend? I did not find it

**Comment by larshp** [comment]
class https://github.com/abaplint/abaplint-abap-backend/blob/master/src/deps/zcl_abaplint_deps_find.clas.abap finds the dependencies

**Comment by ed-holland** [comment]
The finding is not the problem. Generating to sources is what i am missing and committing them like in the deps abap.

**Comment by ed-holland** [comment]
Found the program ... issue is the same. Will close this one and create a new in the other repo.
